  type id = string
  type index = int
  type uttyp = (string, (string * Context.context)) Ast.annotated_typ
  type texpr = (annotated_texpr, id, uttyp) Ast.annotated_expr
  and annotated_texpr =  (texpr * (Lexing.position * uttyp))
  type utstmt = (annotated_utstmt, annotated_texpr, id, uttyp, index) Ast.annotated_stmt
  and annotated_utstmt = utstmt * Lexing.position
  type utdecl = (annotated_utstmt, annotated_texpr, id, uttyp, index) Ast.annotated_decl
  type annotated_utdecl = utdecl * Lexing.position
  type ast  = (annotated_utdecl, id) Ast.annotated_ast
